package com.example.springai.rag.config;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.openaisdk.OpenAiSdkChatModel;
import org.springframework.ai.vectorstore.SimpleVectorStore;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration class for Spring AI RAG components.
 * 
 * The OpenAI SDK starter (spring-ai-starter-model-openai-sdk) auto-configures
 * both OpenAiSdkChatModel and OpenAiSdkEmbeddingModel using properties
 * from application.yaml. Azure mode is detected automatically when the
 * base URL contains openai.azure.com.
 * 
 * This config provides the ChatClient and VectorStore beans that build
 * on the auto-configured models.
 *
 * 💡 Ask GitHub Copilot:
 * - "Why does this module expose ChatClient (not just ChatModel) — what does the advisor path need?"
 * - "SimpleVectorStore is in-memory — how would I migrate to Azure AI Search without rewriting services?"
 * - "How do I configure a separate embedding deployment from the chat deployment?"
 * - "How can I verify my embeddings are being generated by the intended model at startup?"
 */
@Configuration
public class SpringAiRagConfig {

    /**
     * Creates a ChatClient for the advisor-based RAG approach.
     * ChatClient provides a fluent API for building prompts with advisors.
     *
     * @return configured ChatClient
     */
    @Bean
    public ChatClient chatClient(OpenAiSdkChatModel chatModel) {
        return ChatClient.builder(chatModel).build();
    }

    /**
     * Creates an in-memory vector store for development.
     * This store loses all data when the application restarts.
     *
     * @return in-memory vector store
     */
    @Bean
    public VectorStore vectorStore(EmbeddingModel embeddingModel) {
        return SimpleVectorStore.builder(embeddingModel).build();
    }
}
