package com.example.springai.app;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Simple REST controller exposing a stateless chat endpoint.
 * Delegates requests to a {@link ChatClient} built from the auto-configured
 * {@link ChatClient.Builder} provided by {@code spring-ai-starter-model-openai}.
 *
 * This controller demonstrates basic stateless chat completion without memory.
 * For conversational chat with history, see {@link ConversationController}.
 *
 * 💡 Ask GitHub Copilot:
 * - "Why is this controller stateless — what would change if I added MessageChatMemoryAdvisor here?"
 * - "How would I stream responses back to the client using ChatClient's reactive `stream()` API?"
 * - "How could I add a system prompt to shape the assistant's persona for every request?"
 * - "What does ChatClient give me on top of OpenAiChatModel — fluent prompts, advisors, what else?"
 */
@RestController
@RequestMapping("/api/chat")
public class ChatController {

  private final ChatClient chatClient;

  /**
   * Constructor injection of the auto-configured {@link ChatClient.Builder}.
   * Each consumer builds its own ChatClient so advisors stay scoped per use-case
   * (this stateless endpoint deliberately wires no memory advisor).
   *
   * @param chatClientBuilder auto-configured by spring-ai-starter-model-openai
   */
  public ChatController(ChatClient.Builder chatClientBuilder) {
    this.chatClient = chatClientBuilder.build();
  }

  /**
   * Accept a JSON payload containing a "message" and return a
   * response generated by the underlying Microsoft Foundry model. Example
   * request: {"message":"Hello"}
   */
  @PostMapping
  public ResponseEntity<Map<String, Object>> chat(@RequestBody Map<String, String> body) {
    String prompt = body.getOrDefault("message", "Hello");
    try {
      String answer = chatClient.prompt(prompt).call().content();
      return ResponseEntity.ok(Map.of("prompt", prompt, "answer", answer));
    } catch (Exception e) {
      // Propagate error details back to the client
      return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
          .body(Map.of(
              "prompt", prompt,
              "error", e.getMessage() != null ? e.getMessage() : "Unknown error"
          ));
    }
  }

  /**
   * Simple health check endpoint used by deployment probes.
   */
  @GetMapping("/health")
  public Map<String, String> health() {
    return Map.of("status", "ok");
  }
}