package com.example.springai.app;

import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.openaisdk.OpenAiSdkChatModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Simple REST controller exposing a chat endpoint.
 * Delegates requests to the OpenAiSdkChatModel provided by Spring AI.
 * 
 * This controller demonstrates basic stateless chat completion without memory.
 * For conversational chat with history, see {@link ConversationController}.
 *
 * 💡 Ask GitHub Copilot:
 * - "Why is this controller stateless — what would change if I added ChatMemory here?"
 * - "How would I stream responses back to the client instead of waiting for the full completion?"
 * - "How could I add a system prompt to shape the assistant's persona for every request?"
 * - "What's the benefit of using OpenAiSdkChatModel directly vs wrapping it with ChatClient?"
 */
@RestController
@RequestMapping("/api/chat")
public class ChatController {

  private final OpenAiSdkChatModel chatModel;

  /**
   * Constructor injection of the chat model bean.
   * Model is manually configured as a Spring bean (see SpringAiConfig.java).
   *
   * @param chatModel configured OpenAI SDK chat model
   */
  public ChatController(OpenAiSdkChatModel chatModel) {
    this.chatModel = chatModel;
  }

  /**
   * Accept a JSON payload containing a "message" and return a
   * response generated by the underlying Azure model.  Example
   * request: {"message":"Hello"}
   */
  @PostMapping
  public ResponseEntity<Map<String, Object>> chat(@RequestBody Map<String, String> body) {
    String prompt = body.getOrDefault("message", "Hello");
    try {
      String answer = chatModel.call(new Prompt(prompt)).getResult().getOutput().getText();
      return ResponseEntity.ok(Map.of("prompt", prompt, "answer", answer));
    } catch (Exception e) {
      // Propagate error details back to the client
      return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
          .body(Map.of(
              "prompt", prompt,
              "error", e.getMessage() != null ? e.getMessage() : "Unknown error"
          ));
    }
  }

  /**
   * Simple health check endpoint used by deployment probes.
   */
  @GetMapping("/health")
  public Map<String, String> health() {
    return Map.of("status", "ok");
  }
}