spring:
  application:
    name: tictactoe-client
  main:
    web-application-type: servlet
  ai:
    mcp:
      client:
        request-timeout: 30s
        streamable-http:
          connections:
            tictactoe-server:
              url: http://localhost:8080

server:
  port: 8081

logging:
  level:
    "[com.example.springai]": INFO
    "[io.modelcontextprotocol.client]": WARN
    "[io.modelcontextprotocol.spec]": WARN
