spring:
  main:
    banner-mode: off
  ai:
    openai:
      base-url: ${AZURE_OPENAI_ENDPOINT}
      api-key: ${AZURE_OPENAI_API_KEY}
      microsoft-deployment-name: ${AZURE_OPENAI_FAST_DEPLOYMENT}
      chat:
        model: ${AZURE_OPENAI_FAST_DEPLOYMENT}
    mcp:
      server:
        name: tictactoe-server
        version: 1.0.0
        protocol: STREAMABLE
        request-timeout: 30s

server:
  port: 8085

logging:
  level:
    "[com.example.springai]": INFO
